config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  get    '/signup',           to: 'users#new'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  delete '/logout',           to: 'sessions#destroy'

  post '/tasks/:id/toggle', to: 'tasks#toggle'

  resources :tasks
  resources :task_lists
  resources :users
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :task
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: :true
  validates :password, presence: :true
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true
  belongs_to :task_list
  has_many :comments
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  validates :content, presence: true
  has_many :tasks
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :comments
  has_many :projects, foreign_key: :owner_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def hello
    render html: "hello,world!"
  end
  protect_from_forgery with: :null_session
  
  include SessionsHelper
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        # ユーザーのログイン状態の判定
        if logged_in?
            # コメントの情報を取得、レコードの生成
            @task = Task.find(params[:comment][:id])
            @comment = @task.comments.build(comment_params)
            @comment.user_id = current_user.id
            
            # レコードの保存
            @comment.save
            redirect_to task_path(@task.id)
        else
            redirect_to login_path
        end
    end

    def update
        # レコードの取得
        @comment = current_user.comments.find_by(id: params[:id])
        task_id = @comment.task.id

        # レコードの更新
        @comment.update(content: params[:content])
        redirect_back fallback_location: task_path(task_id)
    end

    def destroy
        # レコードの取得
        @comment = current_user.comments.find_by(id: params[:id])
        task_id = @comment.task.id

        # レコードの削除
        @comment.destroy
        redirect_back fallback_location: task_path(task_id)
    end

    private
        def comment_params
            params.require(:comment).permit(:content)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to task_lists_path
    else
      flash.now[:danger] = 'Invalid email/password combination' # 本当は正しくない
      # エラーメッセージを作成する
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  
  def index
    # form-tagのmodel名と揃える必要がある
    @task_list = TaskList.new
    @lists = TaskList.all
  end
  
  def create
    @list = TaskList.new(task_list_params)
    
    if @list.save
      redirect_to task_lists_path
    else
      render 'index'
    end
  end
  
  def show
    @task = Task.new
    @list = TaskList.find(params[:id])
    tasks = Task.all
    
    # false true　それぞれの空配列を作る
    @task_false = []
    @task_true = []
    
    # false true それぞれ条件に合うものに入れ込む
    tasks.each {|task| @task_false.push(task) if task.status == false && task.task_list_id == @list.id }
    tasks.each {|task| @task_true.push(task) if task.status == true && task.task_list_id == @list.id }
  end
  
  private
    
    def task_list_params
      params.require(:task_list).permit(:content)
    end
  
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @task = Task.new
    tasks = Task.all
    
    @task_false = []
    @task_true = []
    
    tasks.each {|task| @task_false.push(task) if task.status == false }
    tasks.each {|task| @task_true.push(task) if task.status == true }
  end
  
  def create
    @list = TaskList.find(params[:task][:id])
    @task = @list.tasks.build(task_params)

    if @task.save
      redirect_to task_list_path(@list.id)
    else
      render 'new'
    end
  end
  
  # def show
  #   tasks = Task.all
    
  #   # false true　それぞれを入れう空配列を作る
  #   @task_false = []
  #   @task_true = []
    
  #   # false true それぞれ条件に合うものに入れ込む
  #   tasks.each {|task| @task_false.push(task) if task.status == false }
  #   tasks.each {|task| @task_true.push(task) if task.status == true }
  # end
  
  def show
    @comment = Comment.new
    task = Task.find(params[:id])
    com = Comment.all

    # 指定の「task_id」持ちのコメント一覧を取得
    @comments = []
    com.each {|i| @comments.push(i) if i.task_id == task.id }
  end

  # taskのチェックボックスクリック時にステータスを変更
  def toggle
    @task = Task.find(params[:id])
    # task_list = @task.task_list_id
    
    # タスクstatusの値を反対に返す
    @task.status = !@task.status
    @task.save
    
    # render nothing: true
    # 上記のrenderはrails5から使えなくなったので下記の方法を利用
    redirect_to task_list_path(@task.task_list_id)

  end
  
    private
    
      def task_params
        params.require(:task).permit(:content)
      end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    tasks = Task.all
    
     # false true　それぞれの空配列を作る
    @task_false = []
    @task_true = []
    
    # false true それぞれ条件に合うものに入れ込む
    tasks.each {|task| @task_false.push(task) if task.status == false }
    tasks.each {|task| @task_true.push(task) if task.status == true }
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success ] = "Welcome to your Task list!"
      redirect_to task_lists_path
    else
      render 'new'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  # 渡されたユーザーがカレントユーザーなのか確認
  def current_user?(user)
    user && user == current_user
  end
  
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

    # タスクがある時true、ない時はfalseを返す
    def have_task?(task)
        !(task.empty?)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
    <div>
        <p><%= comment.user.name %></p>
        <p><%= comment.content %></p>

        <% if current_user?(comment.user) %>
            <button class="edit_button">edit</button>

            <%= form_with(local: true, url: comment_path(comment), method: :patch, class: 'edit_form') do |f| %>
                <%= f.text_field :content %>
                <input type="button" class="edit_close" value="キャンセル">
                <%= f.submit "更新" ,class: "btn btn-green" %>
            <% end %>
            <%= link_to 'delete', comment_path(comment), method: :delete %>
        <% end %>
        <hr>
    </div>
<% end %>

app/views/comments/index.html.erb
<div>Comments</div>
<%= form_with(model: @comment, local: true) do |f| %>
    <%= f.label :コメントの追加 %>
    <%= f.text_field :content %>
    
    <%= f.submit "作成", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if !(logged_in?) %>
          <li><%= link_to "Signup",   signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% else %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_new.html.erb
<%= form_with(model: @task, local: true) do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    
    <%= f.submit "作成", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackathonApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= session[:user_id] %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
    <!-- jqueryの機能を使ってチェックボックスの制御を行う -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(function() {
            $("input[type=checkbox]").click(function() {
                $.post('/tasks/'+$(this).data('id')+'/toggle')
            })
        })
    </script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/task_lists/index.html.erb
<%= form_with(model: @task_list, local: true) do |f| %>
    <%= f.label :リストの追加 %>
    <%= f.text_field :content %>
    
    <%= f.submit "作成", class: "btn btn-primary" %>
<% end %>

<% @lists.each do |list| %>
  <div><%= link_to list.content, task_list_path(list.id) %></div>
<% end %>

app/views/task_lists/show.html.erb
<h1>タスクリスト</h1>
<%= form_with(model: @task, local: true) do |f| %>
    <%= f.label :タスクの追加 %>
    <%= f.text_field :content %>
    
    <%= f.hidden_field :id, :value => params[:id] %>
    
    <%= f.submit "作成", class: "btn btn-primary" %>
<% end %>

<% if have_task?(@task_false) %>
  <h1>未処理タスク</h1>
  <% @task_false.each do |task| %>
    <div><%= check_box_tag '', '', task.status, {'data-id' => task.id} %> <%= link_to task.content, task_path(task.id) %></div>
  <% end %>
<% else %>
  <p>現在タスクはありません。</p>
<% end %>

<% if have_task?(@task_true) %>
  <h1>終了タスク</h1>
  <% @task_true.each do |task| %>
    <div><%= check_box_tag '', '', task.status, {'data-id' => task.id} %> <%= link_to task.content, task_path(task.id) %></div>
  <% end %>
<% end %>

app/views/tasks/index.html.erb
<%= render 'layouts/new' %>

<h1>未処理タスク</h1>
<% @task_false.each do |task| %>
  <div><%= check_box_tag '', '', task.status, {'data-id' => task.id} %> <%= task.content %></div>
<% end %>
<h1>終了タスク</h1>
<% @task_true.each do |task| %>
  <div><%= check_box_tag '', '', task.status, {'data-id' => task.id} %> <%= task.content %></div>
<% end %>
<h1><%= p @user %></h1>

app/views/tasks/show.html.erb
<h1>Comments</h1>
<%= form_with(model: @comment, local: true) do |f| %>
    <%= f.label :コメントの追加 %>
    <%= f.text_field :content %>

    <%= f.hidden_field :id, :value => params[:id] %>
    
    <%= f.submit "作成", class: "btn btn-primary" %>
<% end %>

<%= render @comments %>

<script>
    // editボタンクリック時
    $('.edit_button').click(function(){
        // editボタン・コメントを非表示
        $(this).prev().hide();
        $(this).hide();

        // edit_formの表示
        $(this).next('.edit_form').show();
    })

    // キャンセルボタンクリック時
    $('.edit_close').click(function(){
        // edit_formの表示
        $(this).parent('.edit_form').hide();

        // editボタン・コメントを表示
        $(this).parent().prevAll().show();
    })
</script>

app/views/users/new.html.erb
<h1 class = "signup_caption">Sign Up</h1>

<div class = "row">
  
  <div class = "col-md-6 col-md-offset-3">
    
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      
    <% end %>
    
    
  </div>
  
</div>

app/views/users/show.html.erb
<%= render 'layouts/new' %>

<h1>未処理タスク</h1>
<% @task_false.each do |task| %>
  <div><%= check_box_tag '', '', task.status, {'data-id' => task.id} %> <%= task.content %></div>
<% end %>
<h1>終了タスク</h1>
<% @task_true.each do |task| %>
  <div><%= check_box_tag '', '', task.status, {'data-id' => task.id} %> <%= task.content %></div>
<% end %>